# Generated by Django 5.1.4 on 2024-12-31 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='chat_communitydata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_id', models.CharField(blank=True, max_length=20, null=True)),
                ('user_id', models.CharField(blank=True, max_length=20, null=True)),
                ('community_id', models.CharField(blank=True, max_length=20, null=True)),
                ('content_type', models.CharField(max_length=20)),
                ('messagecontent', models.CharField(max_length=40)),
                ('sent_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'chat_communitydata',
            },
        ),
        migrations.CreateModel(
            name='community_chat_data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_id', models.CharField(blank=True, max_length=90, null=True)),
                ('user_id', models.CharField(blank=True, max_length=20, null=True)),
                ('community_id', models.CharField(blank=True, max_length=20, null=True)),
                ('content_type', models.CharField(max_length=20)),
                ('messagecontent', models.CharField(max_length=40)),
                ('media_content', models.FileField(blank=True, null=True, upload_to='uploads/')),
                ('media_caption', models.CharField(blank=True, max_length=250, null=True)),
                ('sent_date', models.DateTimeField(auto_now_add=True)),
                ('editted', models.CharField(blank=True, max_length=15, null=True)),
            ],
            options={
                'db_table': 'chat_community_data',
            },
        ),
        migrations.CreateModel(
            name='create_community',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('community_id', models.CharField(blank=True, max_length=10, null=True)),
                ('community_name', models.CharField(max_length=30)),
                ('community_image', models.FileField(blank=True, null=True, upload_to='profile/')),
                ('creator_id', models.CharField(blank=True, max_length=15, null=True)),
                ('creator_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'Create_community',
            },
        ),
        migrations.CreateModel(
            name='follower',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_id', models.CharField(blank=True, max_length=20, null=True)),
                ('to_id', models.CharField(blank=True, max_length=20, null=True)),
                ('posted_on', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'followers_details',
            },
        ),
        migrations.CreateModel(
            name='post_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_id', models.CharField(blank=True, max_length=60, null=True)),
                ('posted_by', models.CharField(blank=True, max_length=20, null=True)),
                ('media', models.FileField(blank=True, null=True, upload_to='post/')),
                ('caption', models.CharField(blank=True, max_length=450, null=True)),
                ('posted_on', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'Post_details',
            },
        ),
        migrations.CreateModel(
            name='user_community',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(blank=True, max_length=20, null=True)),
                ('community_id', models.CharField(blank=True, max_length=20, null=True)),
                ('role', models.CharField(blank=True, default='follower', max_length=10, null=True)),
            ],
            options={
                'db_table': 'User_community',
            },
        ),
        migrations.CreateModel(
            name='user_detail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_photo', models.FileField(blank=True, null=True, upload_to='userprofile/')),
                ('user_id', models.CharField(blank=True, max_length=20, null=True)),
                ('name', models.CharField(blank=True, max_length=90, null=True)),
                ('bio', models.CharField(blank=True, max_length=150, null=True)),
            ],
            options={
                'db_table': 'User_profile',
            },
        ),
    ]
