# Generated by Django 5.1.3 on 2025-01-30 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='community_chat_data',
            name='media_content',
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='create_community',
            name='community_image',
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='post_details',
            name='media',
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user_detail',
            name='profile_photo',
            field=models.BinaryField(blank=True, null=True),
        ),
    ]
