# Generated by Django 5.1.5 on 2025-02-25 09:31

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='banneruploadstartup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banner1', models.BinaryField(blank=True, null=True)),
                ('banner2', models.BinaryField(blank=True, null=True)),
                ('banner3', models.BinaryField(blank=True, null=True)),
            ],
            options={
                'db_table': 'startupbanner',
            },
        ),
        migrations.CreateModel(
            name='CostCuttingCategoryMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categroy_name', models.CharField(default='General Category', max_length=50)),
                ('category_image', models.BinaryField(blank=True, null=True)),
            ],
            options={
                'db_table': 'costcuttingcategorymaster',
            },
        ),
        migrations.CreateModel(
            name='EventsAndUpdates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banner1', models.ImageField(upload_to='banners/', verbose_name='Banner 1')),
            ],
            options={
                'db_table': 'eventsandupdates',
            },
        ),
        migrations.CreateModel(
            name='InternNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=255)),
                ('notification', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Intern Notification',
                'verbose_name_plural': 'Intern Notifications',
                'db_table': 'intern_notifications',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(blank=True, max_length=30, null=True)),
                ('name', models.CharField(default='Unnamed Member', max_length=100)),
                ('category', models.CharField(default='General', max_length=50)),
                ('college_name', models.CharField(default='Unknown College', max_length=200)),
                ('year', models.IntegerField(default=2024)),
                ('domain', models.CharField(default='General', max_length=100)),
                ('startup_id', models.CharField(blank=True, max_length=50, null=True)),
                ('ep1', models.CharField(blank=True, max_length=300, null=True)),
            ],
            options={
                'db_table': 'members',
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_number', models.IntegerField()),
                ('category_name', models.CharField(max_length=255)),
                ('question', models.TextField()),
                ('option1', models.CharField(max_length=255)),
                ('efficiency_1', models.IntegerField()),
                ('description_1', models.TextField(blank=True, null=True)),
                ('option2', models.CharField(max_length=255)),
                ('efficiency_2', models.IntegerField()),
                ('description_2', models.TextField(blank=True, null=True)),
                ('option3', models.CharField(max_length=255)),
                ('efficiency_3', models.IntegerField()),
                ('description_3', models.TextField(blank=True, null=True)),
                ('option4', models.CharField(max_length=255)),
                ('efficiency_4', models.IntegerField()),
                ('description_4', models.TextField(blank=True, null=True)),
                ('correct_option', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'costcuttingquestions',
            },
        ),
        migrations.CreateModel(
            name='startup_individual_score',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.TextField(blank=True, null=True)),
                ('startup_id', models.TextField(blank=True, null=True)),
                ('game_name', models.TextField(blank=True, null=True)),
                ('score', models.TextField(blank=True, null=True)),
                ('category', models.TextField(blank=True, null=True)),
                ('attribute1', models.DateTimeField(auto_now_add=True)),
                ('attribute2', models.TextField(blank=True, null=True)),
                ('attribute3', models.TextField(blank=True, null=True)),
                ('attribute4', models.TextField(blank=True, null=True)),
                ('attribute5', models.TextField(blank=True, null=True)),
                ('attribute6', models.TextField(blank=True, null=True)),
                ('attribute7', models.TextField(blank=True, null=True)),
                ('attribute8', models.TextField(blank=True, null=True)),
                ('attribute9', models.TextField(blank=True, null=True)),
                ('attribute10', models.TextField(blank=True, null=True)),
                ('attribute11', models.TextField(blank=True, null=True)),
                ('attribute12', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'individual_startup_game_score',
            },
        ),
        migrations.CreateModel(
            name='StartupRegistartion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(blank=True, max_length=30, null=True)),
                ('startup_Name', models.CharField(max_length=30)),
                ('founder_Name', models.CharField(max_length=50)),
                ('founded_date', models.CharField(max_length=20)),
                ('contact_email', models.CharField(max_length=50)),
                ('contact_phonenumber', models.CharField(max_length=15)),
                ('sector', models.CharField(max_length=30)),
                ('company_stage', models.CharField(max_length=30)),
                ('employee_count', models.CharField(max_length=10)),
                ('Funding_Received', models.CharField(max_length=30)),
                ('Key_technology', models.CharField(max_length=50)),
                ('Address_line_1', models.CharField(max_length=30)),
                ('Area', models.CharField(max_length=15)),
                ('city', models.CharField(max_length=15)),
                ('state', models.CharField(max_length=15)),
                ('zipcode', models.CharField(max_length=6)),
                ('Focus_area', models.CharField(max_length=25)),
                ('Funding_duration', models.CharField(max_length=15)),
                ('Linkedin_link', models.CharField(max_length=100)),
                ('Github_link', models.CharField(max_length=100)),
                ('Pitch_deck_link', models.CharField(max_length=100)),
                ('reason', models.CharField(max_length=300)),
                ('status', models.CharField(blank=True, max_length=300, null=True)),
                ('ep1', models.CharField(blank=True, max_length=300, null=True)),
                ('ep2', models.CharField(blank=True, max_length=300, null=True)),
                ('ep3', models.CharField(blank=True, max_length=300, null=True)),
                ('ep4', models.CharField(blank=True, max_length=300, null=True)),
                ('ep5', models.CharField(blank=True, max_length=300, null=True)),
            ],
            options={
                'db_table': 'Startup_Registartion',
            },
        ),
        migrations.CreateModel(
            name='startupscore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('startup_id', models.TextField(blank=True, null=True)),
                ('game_name', models.TextField(blank=True, null=True)),
                ('score', models.TextField(blank=True, null=True)),
                ('category', models.TextField(blank=True, null=True)),
                ('attribute1', models.TextField(blank=True, null=True)),
                ('attribute2', models.TextField(blank=True, null=True)),
                ('attribute3', models.TextField(blank=True, null=True)),
                ('attribute4', models.TextField(blank=True, null=True)),
                ('attribute5', models.TextField(blank=True, null=True)),
                ('attribute6', models.TextField(blank=True, null=True)),
                ('attribute7', models.TextField(blank=True, null=True)),
                ('attribute8', models.TextField(blank=True, null=True)),
                ('attribute9', models.TextField(blank=True, null=True)),
                ('attribute10', models.TextField(blank=True, null=True)),
                ('attribute11', models.TextField(blank=True, null=True)),
                ('attribute12', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'startup_game_score',
            },
        ),
        migrations.CreateModel(
            name='StudentReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.CharField(max_length=25)),
                ('title', models.CharField(max_length=50)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('strengths', models.JSONField()),
                ('weakness', models.JSONField()),
                ('opportunity', models.JSONField()),
                ('threat', models.JSONField()),
                ('improvements', models.JSONField(blank=True, null=True)),
                ('addons', models.JSONField(blank=True, null=True)),
            ],
            options={
                'db_table': 'swotanalysis',
            },
        ),
        migrations.CreateModel(
            name='TeamCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='Team ID')),
                ('team_category', models.CharField(max_length=50, unique=True, verbose_name='Team Category')),
            ],
            options={
                'db_table': 'team_category',
            },
        ),
        migrations.CreateModel(
            name='Userauth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=13, unique=True)),
                ('username', models.CharField(max_length=85)),
                ('password', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'user_authenthication',
            },
        ),
    ]
