# Generated by Django 5.1.4 on 2025-01-04 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='startup_individual_score',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.TextField(blank=True, null=True)),
                ('startup_id', models.TextField(blank=True, null=True)),
                ('game_name', models.TextField(blank=True, null=True)),
                ('score', models.TextField(blank=True, null=True)),
                ('category', models.TextField(blank=True, null=True)),
                ('attribute1', models.TextField(blank=True, null=True)),
                ('attribute2', models.TextField(blank=True, null=True)),
                ('attribute3', models.TextField(blank=True, null=True)),
                ('attribute4', models.TextField(blank=True, null=True)),
                ('attribute5', models.TextField(blank=True, null=True)),
                ('attribute6', models.TextField(blank=True, null=True)),
                ('attribute7', models.TextField(blank=True, null=True)),
                ('attribute8', models.TextField(blank=True, null=True)),
                ('attribute9', models.TextField(blank=True, null=True)),
                ('attribute10', models.TextField(blank=True, null=True)),
                ('attribute11', models.TextField(blank=True, null=True)),
                ('attribute12', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'individual_startup_game_score',
            },
        ),
        migrations.CreateModel(
            name='startupscore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('startup_id', models.TextField(blank=True, null=True)),
                ('game_name', models.TextField(blank=True, null=True)),
                ('score', models.TextField(blank=True, null=True)),
                ('category', models.TextField(blank=True, null=True)),
                ('attribute1', models.TextField(blank=True, null=True)),
                ('attribute2', models.TextField(blank=True, null=True)),
                ('attribute3', models.TextField(blank=True, null=True)),
                ('attribute4', models.TextField(blank=True, null=True)),
                ('attribute5', models.TextField(blank=True, null=True)),
                ('attribute6', models.TextField(blank=True, null=True)),
                ('attribute7', models.TextField(blank=True, null=True)),
                ('attribute8', models.TextField(blank=True, null=True)),
                ('attribute9', models.TextField(blank=True, null=True)),
                ('attribute10', models.TextField(blank=True, null=True)),
                ('attribute11', models.TextField(blank=True, null=True)),
                ('attribute12', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'startup_game_score',
            },
        ),
    ]
