# Generated by Django 5.1.3 on 2025-01-30 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0003_costcuttingcategorymaster_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='banneruploadstartup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banner1', models.BinaryField(blank=True, null=True)),
                ('banner2', models.BinaryField(blank=True, null=True)),
                ('banner3', models.BinaryField(blank=True, null=True)),
            ],
            options={
                'db_table': 'startupbanner',
            },
        ),
        migrations.CreateModel(
            name='StartupRegistartion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(blank=True, max_length=30, null=True)),
                ('startup_Name', models.CharField(max_length=30)),
                ('founder_Name', models.CharField(max_length=50)),
                ('founded_date', models.CharField(max_length=20)),
                ('contact_email', models.CharField(max_length=50)),
                ('contact_phonenumber', models.CharField(max_length=15)),
                ('sector', models.CharField(max_length=30)),
                ('company_stage', models.CharField(max_length=30)),
                ('employee_count', models.CharField(max_length=10)),
                ('Funding_Received', models.CharField(max_length=30)),
                ('Key_technology', models.CharField(max_length=50)),
                ('Address_line_1', models.CharField(max_length=30)),
                ('Area', models.CharField(max_length=15)),
                ('city', models.CharField(max_length=15)),
                ('state', models.CharField(max_length=15)),
                ('zipcode', models.CharField(max_length=6)),
                ('Focus_area', models.CharField(max_length=25)),
                ('Funding_duration', models.CharField(max_length=15)),
                ('Linkedin_link', models.CharField(max_length=100)),
                ('Github_link', models.CharField(max_length=100)),
                ('Pitch_deck_link', models.CharField(max_length=100)),
                ('reason', models.CharField(max_length=300)),
                ('status', models.CharField(blank=True, max_length=300, null=True)),
                ('ep1', models.CharField(blank=True, max_length=300, null=True)),
                ('ep2', models.CharField(blank=True, max_length=300, null=True)),
                ('ep3', models.CharField(blank=True, max_length=300, null=True)),
                ('ep4', models.CharField(blank=True, max_length=300, null=True)),
                ('ep5', models.CharField(blank=True, max_length=300, null=True)),
            ],
            options={
                'db_table': 'Startup_Registartion',
            },
        ),
    ]
