# Generated by Django 5.1.5 on 2025-02-23 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0004_banneruploadstartup_startupregistartion'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventsAndUpdates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banner1', models.ImageField(upload_to='banners/', verbose_name='Banner 1')),
            ],
            options={
                'db_table': 'eventsandupdates',
            },
        ),
        migrations.CreateModel(
            name='InternNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=255)),
                ('notification', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Intern Notification',
                'verbose_name_plural': 'Intern Notifications',
                'db_table': 'intern_notifications',
                'ordering': ['-created_at'],
            },
        ),
    ]
