# Generated by Django 5.1.6 on 2025-03-04 13:29

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internship', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bannerupload',
            name='uploaded_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bannerupload',
            name='banner1',
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bannerupload',
            name='banner2',
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bannerupload',
            name='banner3',
            field=models.BinaryField(blank=True, null=True),
        ),
    ]
