# Generated by Django 5.1.4 on 2024-12-31 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AddInvestor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login_id', models.TextField(blank=True, null=True)),
                ('investor_name', models.CharField(max_length=255)),
                ('company_name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('contact_number', models.CharField(max_length=15)),
                ('email_id', models.EmailField(max_length=254)),
                ('visiting_card', models.BinaryField(blank=True, null=True)),
                ('purpose', models.CharField(blank=True, max_length=255, null=True)),
                ('meeting_date', models.DateField(blank=True, null=True)),
                ('meeting_time', models.TimeField(blank=True, null=True)),
                ('attribute1', models.TextField(blank=True, null=True)),
                ('attribute2', models.TextField(blank=True, null=True)),
                ('attribute3', models.TextField(blank=True, null=True)),
                ('attribute4', models.TextField(blank=True, null=True)),
                ('attribute5', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'investors',
            },
        ),
        migrations.CreateModel(
            name='AddVendor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login_id', models.TextField(blank=True, null=True)),
                ('company_name', models.CharField(max_length=255)),
                ('marketing_person_name', models.CharField(max_length=255)),
                ('official_contact_number', models.CharField(max_length=15)),
                ('official_mail_id', models.EmailField(max_length=254)),
                ('contact_person_mail_id', models.EmailField(max_length=254)),
                ('contact_person_contact_number', models.CharField(max_length=15)),
                ('company_address', models.TextField()),
                ('description', models.TextField()),
                ('agreement_upload', models.BinaryField()),
                ('attribute1', models.TextField(blank=True, null=True)),
                ('attribute2', models.TextField(blank=True, null=True)),
                ('attribute3', models.TextField(blank=True, null=True)),
                ('attribute4', models.TextField(blank=True, null=True)),
                ('attribute5', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'vendors',
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login_id', models.TextField(blank=True, null=True)),
                ('title', models.CharField(max_length=255)),
                ('document_category', models.CharField(choices=[('Agreement', 'Agreement'), ('Invoice', 'Invoice'), ('Purchase Order', 'Purchase Order'), ('MOU', 'MOU'), ('NDA', 'NDA')], max_length=50)),
                ('document_type', models.CharField(choices=[('Received', 'Received'), ('Sent', 'Sent')], max_length=50)),
                ('party_name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('document_upload', models.BinaryField()),
                ('attribute1', models.TextField(blank=True, null=True)),
                ('attribute2', models.TextField(blank=True, null=True)),
                ('attribute3', models.TextField(blank=True, null=True)),
                ('attribute4', models.TextField(blank=True, null=True)),
                ('attribute5', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'document',
            },
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login_id', models.TextField(blank=True, null=True)),
                ('product_name', models.CharField(max_length=255)),
                ('shop_name', models.CharField(max_length=255)),
                ('date_of_purchase', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('invoice', models.BinaryField()),
                ('attribute1', models.TextField(blank=True, null=True)),
                ('attribute2', models.TextField(blank=True, null=True)),
                ('attribute3', models.TextField(blank=True, null=True)),
                ('attribute4', models.TextField(blank=True, null=True)),
                ('attribute5', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'expense',
            },
        ),
        migrations.CreateModel(
            name='Scheduler',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login_id', models.TextField(blank=True, null=True)),
                ('title', models.CharField(max_length=255)),
                ('due_date', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('attribute1', models.TextField(blank=True, null=True)),
                ('attribute2', models.TextField(blank=True, null=True)),
                ('attribute3', models.TextField(blank=True, null=True)),
                ('attribute4', models.TextField(blank=True, null=True)),
                ('attribute5', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'scheduler',
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login_id', models.TextField(blank=True, null=True)),
                ('title', models.CharField(max_length=255)),
                ('due_date', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('attribute1', models.TextField(blank=True, null=True)),
                ('attribute2', models.TextField(blank=True, null=True)),
                ('attribute3', models.TextField(blank=True, null=True)),
                ('attribute4', models.TextField(blank=True, null=True)),
                ('attribute5', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'todoList',
            },
        ),
        migrations.CreateModel(
            name='todolistHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_id', models.TextField(blank=True, null=True)),
                ('to_id', models.TextField(blank=True, null=True)),
                ('reason', models.TextField(blank=True, null=True)),
                ('reassign_at', models.DateTimeField(auto_now_add=True)),
                ('due_date', models.DateTimeField()),
                ('startup_id', models.TextField(blank=True, null=True)),
                ('attribute1', models.TextField(blank=True, null=True)),
                ('attribute2', models.TextField(blank=True, null=True)),
                ('attribute3', models.TextField(blank=True, null=True)),
                ('attribute4', models.TextField(blank=True, null=True)),
                ('attribute5', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'todolist_history',
            },
        ),
    ]
