# Generated by Django 5.1.4 on 2025-01-06 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AI_tools', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='document_category',
            field=models.CharField(choices=[('Agreement', 'Agreement'), ('Invoice', 'Invoice'), ('Purchase Order', 'Purchase Order'), ('MOU', 'MOU'), ('NDA', 'NDA'), ('NDA', 'NDA'), ('AI', 'AI')], max_length=50),
        ),
        migrations.AlterField(
            model_name='document',
            name='document_type',
            field=models.CharField(choices=[('Received', 'Received'), ('Sent', 'Sent'), ('AI', 'AI')], max_length=50),
        ),
        migrations.AlterField(
            model_name='document',
            name='party_name',
            field=models.CharField(default='self use', max_length=255),
        ),
    ]
